### ISSUE TITLE
Compile Version and Custome Encode Table

### ISSUE THREAD

**Issue by ghost** [mirusu400/HarvestMoon_Translate_Tools#1]
Hi mirusu400...

This tool is amazing. I wanna do some project with my friends, and as you can say i'm not programmer. I dunno how to compiling this. Can you give me the compile version? My Operating System is Windows.

And i don't know what is custome encode table? Can you explain to me in simple way how to get it?

**Comment by mirusu400** [comment]
Hello, which games do you want to do your project?
Usually I written tools as `Python3`, So you can use it with only install `Python`.
But, `Grand Bazzar` and `The Tales of Two Towns`, I've written it as `C`, you need to Visual studio for build. but I've already upload Compiled version, So you can just use it.

About custom encode table, you can more information here: https://github.com/mirusu400/Rune_Factory_Text_Tools
for example, `82a0 82a2` should be `あい` when you use `Shift-JIS` table, but could be `아이` when you use custom table like this:
```
82a0=아
82a2=이
```
 
These codes are written when I was young, So programs are little bit complicated and hard to use. I'll re-write the codes someday, but I don't have much time now.
If you want to do your project, tell me which games you want. I'll re-write the programs which you want first.

**Comment by ghost** [comment]
Harvest Moon DS: The Tale of Two Towns and Harvest Moon DS: Grand Bazaar North America region...

Thank you so much for your help. Now i'm in project Harvest Moon: Friends of Mineral Town translate with my friends. It'll be done in march 12.  Bye the way, i am so amazed with your works. I have seen your userpage and naver too. That was incredible!

**Comment by mirusu400** [comment]
I've found that HM GB has same structure with US and JPN, so you can use my Tools for *.bin and *.text extracting / importing.

The things is about `encoding table` and `fonts`. I'll make US version encoding table ASAP. To add a language other than English or Japanese, you need to create a `custom font glyph` and `custom encoding table`.



I'll help you where you should translate:
* You can extract each files (in NDS) using [Tinke](https://github.com/pleonex/tinke).
* All graphics are in `console_bg_data.bin` and `console_obj_data.bin` and you can modify graphics using [CrystalTile2](https://www.hackromtools.info/crystaltile2/)
* All texts are in `mes_data.bin` and `event_mes_data.bin`
* All fonts are in `font_data.bin`

Ps. I re-writtend *.bin unpacker/packer with `Python`, so you can unpack all the bin files in GB and TToT with only `Python`.

**Comment by ghost** [comment]
All right, thanks for your help. I'll wait for US encoding table. Since i can't speak japanese.

By the way, i know there's a limit character in GB and TToT dialogues. Do you have a solution for this problem? When english is translated to my native language (Indonesian), usually it will be longer. Anyway, thank you so much for your help mirusu. `

Edit. So when i unpack mes_data.bin and event_mes_data.bin, there are lots of hav files. And when i open hav files, it seems just like a code/symbols. I dunno exactly what is it. I'll wait for your help, mirusu.

Edit. So i know now you make a tool to convert script to txt. There is HM_Script_to_Txt.py. But i dunno how to use it. It is not just drag and drop, right? How to use it?

**Comment by mirusu400** [comment]
![image](https://user-images.githubusercontent.com/25397908/107737401-b0212580-6d47-11eb-9527-b214bb23acf7.png)

Nomally, in JPN version of HM GB, support 14 characters per line. (maybe 28 characters per line in US).

I don't know the width of Indonesian font glyphs, and also I didn't analyzed about the structure of font glyphs.
For now, you can only use 14 characters per line, 42 characters per screen.
(Maybe I can find and modify it anyway, but I don't have on much environment because Im in military :cry:)

Also, about the convert, as I said, when you convert between script and text you can use `scripttotxt.py` and `txttoscript.py`. It need to custom encoding table, so please wait a moment while I create a US encoding table. (these may works with JPN version)

**Comment by ghost** [comment]
Ok, thanks mirusu. I'll wait for US encoding table.

Bye the way, I'm trying, just trying. Use scripttotxt.py to convert script to txt, but i can't. I tried using TToT JPN. I tried drag and drop script file. And tried use command prompt to open scripttotxt.py. But it's not working. Anyway, good luck with your military.

**Comment by mirusu400** [comment]
Ok, now I add US encoding table, named `TToT_us.tbl` but it can use both GB and TToT.

The usage of scripttotxt.py is like:
```
python3 scripttotxt.py your_tbl_file your_script_file_or_dir

ex.
python3 scripttotxt.py TToT_us.tbl event_mes_data/
```
by the way, US version of Grand Bazzar use 4-bytes(long type) pointer, even JPN version use 2-bytes(short type) pointer, you should manually change the source code if it works wrong. ( on the scripttotxt.py line 13)
``` diff
-- POINTER_FLAG = GB_FLAG
++ POINTER_FLAG = TTOT_FLAG
```

**Comment by ghost** [comment]
that's it what i got. 
<img width="676" alt="1" src="https://user-images.githubusercontent.com/77479956/107841397-27f55b80-6ded-11eb-96d6-a47c16ffdba4.PNG">

And this is line 13
<img width="704" alt="2" src="https://user-images.githubusercontent.com/77479956/107841425-507d5580-6ded-11eb-9c7a-f4510b786b06.PNG">

where did it go wrong? sorry asking too many questions. Yeah i'm not programmer or programmer student 😢 i'm pharmacy college student.

**Comment by ghost** [comment]
i'll wait for your help, mirusu-san.

I'm not in kidding about want to translate HM TToT to my native language. I am serious.  I need your help, and the tools you have been made. 

This my project with my friends now, HM FoMT.
![147298801_421240158986469_5761428467349920662_n](https://user-images.githubusercontent.com/77479956/107881343-879b5600-6f16-11eb-8787-d1dd2dd4338d.png)
![145558257_175573610989322_6778040584062698924_n](https://user-images.githubusercontent.com/77479956/107881351-91bd5480-6f16-11eb-8fd5-1457aac28b2f.png)

**Comment by mirusu400** [comment]
Trying to set:
``` diff
-- POINTER_FLAG = 4
++ POINTER_FLAG = GB_FLAG
```
if still not works, set
``` diff
-- POINTER_FLAG = GB_FLAG
++ POINTER_FLAG = TTOT_FLAG
```

I can't have much time wasting on programming, so my comment should be late.

**Comment by ghost** [comment]
It still not work, do I need to put the + and - signs too?
